### ISSUE TITLE
Search icon disappears

### ISSUE THREAD

**Issue by thiru112** [webianks/msgs#11]
@webianks if we click search icon and more options button
the options show search option and by clicking back button the search icon disappers

![screenshot_20180821-092412](https://user-images.githubusercontent.com/34017131/44379676-b2161f00-a524-11e8-8504-3843f07bbc7c.png)
![screenshot_20180821-092419](https://user-images.githubusercontent.com/34017131/44379680-b5a9a600-a524-11e8-911a-88b1581b9d59.png)
![screenshot_20180821-092425](https://user-images.githubusercontent.com/34017131/44379682-b6423c80-a524-11e8-9d2c-5cdaedb02f35.png)

**Comment by thiru112** [comment]
@webianks The issue can be resolved if we change in **home_menu.xml** file
change the ` app:showAsAction="always|collapseActionView"` the issue will be fixed

**Comment by webianks** [comment]
Hi @thiru112 Ill update this in next update.

**Comment by webianks** [comment]
@raghavanv97 do you want to fix this?

**Comment by webianks** [comment]
Never mind I fixed that.
