### ISSUE TITLE
logo for HatkeMessenger

### ISSUE THREAD

**Issue by loydjayme25** [webianks/msgs#4]
Good day !
can i submit a logo design for Hatke sir ?

**Comment by webianks** [comment]
Yes, Go ahead.

**Comment by loydjayme25** [comment]
okay sir, i'll do my best for a simple but awesome logo

**Comment by loydjayme25** [comment]
![example](https://user-images.githubusercontent.com/37318022/38498211-394500ac-3c36-11e8-8902-019b03756c28.png)

if you have any suggestions sir, i am open for it.

**Comment by webianks** [comment]
Looks nice. you can update this in the launcher icon and then make a pr and thanks. :100:

**Comment by loydjayme25** [comment]
i do not know how to make a pull request sir, i am a beginner here in github. can i message you on discord ?

**Comment by webianks** [comment]
No problem. You can send me this image in transparent background and send to my email id **webianks@gmail.com**
Meanwhile, you can check [Pull Request Tutorial](https://yangsu.github.io/pull-request-tutorial/)

**Comment by loydjayme25** [comment]
did you received the email sir ?

**Comment by loydjayme25** [comment]
I made a pull request sir. please do check , many thanks !
