### ISSUE TITLE
Contributing a New Logo

### ISSUE THREAD

**Issue by artjeck** [webianks/msgs#6]
Hi developers!
I am a graphic designer, I want to contribute to make a logo on your project, before I start it, I have to ask your permission first 😃
Regards, @artjeck

**Comment by webianks** [comment]
Yes, You can make.

**Comment by artjeck** [comment]
thank you for the response sir, i will prepare as soon as possible

**Comment by artjeck** [comment]
Hi Developers! 
Please give me an explanation of the HatkeMessengger application, it really helps me to create an interesting logo 👍

**Comment by artjeck** [comment]
Hi Developers! @webianks 
I've completed the latest logo for Hatke Messenger, What do you think?
![bg hatke messengger](https://user-images.githubusercontent.com/38141262/40230867-5ce3b340-5ac3-11e8-92f9-ce4a800d394b.jpg)
#### Mockup
![view on ios](https://user-images.githubusercontent.com/38141262/40230911-7a41f532-5ac3-11e8-93e0-cb8e95d20042.jpg)

#### Logo Varian
![color_size_colorcode](https://user-images.githubusercontent.com/38141262/40231286-c657f3bc-5ac4-11e8-99f1-4853ce5e5453.jpg)

![logotype - transparant](https://user-images.githubusercontent.com/38141262/40231296-d5609396-5ac4-11e8-855e-59511b28e3e6.jpg)
![logotype](https://user-images.githubusercontent.com/38141262/40231297-d5a5fb02-5ac4-11e8-9f3c-90f56d4d8ae2.jpg)

#### Benefit and Inprovements
I created this logo with the idea of letter H, and I think it is very suitable to be a logo, I also use an elegant color and beautiful views. I think this latest logo is very skilled and will definitely make this application more users of course.

#### Original Files
All editable is [here ](https://drive.google.com/drive/folders/13J4JQ-2xHMONJ0s-px3nrn4whMkZkASB?usp=sharing)You can Download it ! 
If you want other color variations, it's easy please contact me

**Comment by artjeck** [comment]
Hello Sir, any other requests from the logo?

**Comment by webianks** [comment]
Hey, I liked the logos, but not sure to use them. Thanks, anyways.
