### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [webianks/msgs#7]
Hello, I am a graphics designer and I am willing to submit my design for your project.

**Comment by webianks** [comment]
Yes, Please go ahead.

**Comment by loydjayme25** [comment]
How About this design ? i am open for any suggestions sir !

![proposal](https://user-images.githubusercontent.com/37318022/39915674-1c13137a-553b-11e8-842d-eecf00e84ac7.png)

**Comment by loydjayme25** [comment]
ReadMe Banner

![banner](https://user-images.githubusercontent.com/37318022/39916268-8b89b4e2-553c-11e8-989b-dc22b9f75a72.png)

**Comment by loydjayme25** [comment]
![readme](https://user-images.githubusercontent.com/37318022/39916444-10d71a72-553d-11e8-96b0-c49acec317fc.png)

**Comment by loydjayme25** [comment]
a darker banner, what do you think ?

![darker](https://user-images.githubusercontent.com/37318022/39916956-a248018c-553e-11e8-938c-679d300ff77a.png)

**Comment by webianks** [comment]
Remove BuyHatke Android Developer Hiring

**Comment by loydjayme25** [comment]
![darker](https://user-images.githubusercontent.com/37318022/39920433-9bc55764-5549-11e8-8e1f-ca6412bdefe9.png)

**Comment by loydjayme25** [comment]
is my design okay to you sir ? 
if it is, i will submit a pull request.

**Comment by loydjayme25** [comment]
i already sent a PR sir @webianks .pls do have a check, thanks !

**Comment by webianks** [comment]
Okay.
